#!/usr/bin/env python

"""
	Tool to parse a former(!) Excel (xls) file containing ISBN
	format as specified below as generated by Android App
	LoMag Barcode Scanner free (by LongInt)
	Format:
		first row: header: "item code", "Quantity", "Unit prize", "Serial number"
		first column: ISBN
	First export as CSV
	Output: csv : ISBN, author, title, publisher
"""

"""
	Major issue: https://stackoverflow.com/questions/8542274/python-xlrd-receiving-float-from-excel-text-cell?rq=1
	Solution : none, epic fail
"""

import csv
import isbnlib
import sys
import logging
import argparse
import os

__name__ = "parse_isbn_csv"
__copyright__ = "Copyright 2018, Olaf Zevenboom"
__author__ = "Olaf Zevenboom"
__credits__ = ["Olaf Zevenboom"]
__license__ = "http://www.wtfpl.net/"
__version__ = "0.1"
__status__ = "Development"

# see for current services and limitations: https://pypi.org/project/isbnlib/
#isbn_service = 'openl'
isbn_service = 'wcat'

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

parser = argparse.ArgumentParser(description='ISBN CSV parser')
parser.add_argument('-i', '--input', help='Input filename', required=True)
parser.add_argument('-o', '--output', help='Output filename', required=True)
args = parser.parse_args()

isbncsvfile = args.input
logger.info("About to start parsing ISBN CSV file: %s" % isbncsvfile)

items = []

if os.path.exists(isbncsvfile):
	with open(isbncsvfile) as csvfile:
		itemcount=-1
		readCSV = csv.reader(csvfile, delimiter=',')
		for row in readCSV:
			# first row is header info
			if itemcount>=0:
				itemcode = row[0] # ISBN
				#quantity = row[1]
				#unitprice = row[2]
				#serialnumber = row[3]
				isbn = itemcode # for now we are only interested in the first column: ISBN 
				items.append(isbn)
			itemcount += 1
logger.info("A total of %d alleged ISBN have been read" % itemcount)


for i, item in enumerate(items):
	logger.info("Need to check and lookup ISBN : %s" % item)
	isbn = item # yuk, needs propper verification
	
	#bibtex = isbnlib.registry.bibformatters['bibtex']
	#print(bibtex(isbnlib.meta(isbn, isbn_service)))
	
	book = isbnlib.meta(isbn)
	#print(book)
	book_title = book['Title']
	book_authors = book['Authors']
	book_isbn = isbn # book['ISBN-13']
	book_year = book['Year']
	book_publisher = book['Publisher']
	book_language = book['Language']
	
	print ("item=%d" % i)
	print ("ISBN : %s " % book_isbn)
	print ("  title : %s" % book_title)
	print ("  authors : %s" % book_authors)
	print ("  publisher : %s" % book_publisher)
	print ("  year : %s" % book_year)
	print ("  language : %s" % book_language)
	
print("Finished")
